### ISSUE TITLE
blank screen in user settings

### ISSUE THREAD

**Issue by pikachurus** [mantisbt-plugins/MonProj#1]
Hi!

Trying to use this plugin on users with 'manager' access role in the project:
![image](https://github.com/mantisbt-plugins/MonProj/assets/16227309/99516129-f49b-4529-a770-362233b3964f)

when user switch to 'monitor projects' tab - he sees a blank screen:
![image](https://github.com/mantisbt-plugins/MonProj/assets/16227309/89d894b5-cbb6-4445-a124-3e0fa8efe5a5)

if i (with administrator role) open this tab, i see projects to choose:
![image](https://github.com/mantisbt-plugins/MonProj/assets/16227309/99b57029-e891-470b-ba18-443bf1b559da)

but can't use drop-down list 'All Project' and 'username' at right top menu, until i switch to another (any) tab

**Comment by ghost** [comment]
All fixed kin version 1.10

**Comment by pikachurus** [comment]
it seems problem still here.

users can't get access to setting page 'monitor project' (blank screen) if they don't have _global_ role 'administrator' to whole mantisbt instance.

**Comment by ghost** [comment]
You are correct, I validated the wrong setting. Can you dowload manage_monitor.php (pages section) again and try again, should be fine now!

**Comment by pikachurus** [comment]
something strange is happening.

couple of days it works fine, but now it happens again.

mantisbt installation the same - no new plugins or changes configuration in projects, it just stop works with same symptoms.

tried to reinstall plugin - doesn't help

**Comment by ghost** [comment]
Are you getting the same blank screen?

**Comment by pikachurus** [comment]
yes, account global role 'reporter', in project role 'developer'

in plugin configuration access to monitoring for role 'developer'
https://i.imgur.com/uM20QPh.png
https://i.imgur.com/soisg7z.png

configuration:
https://i.imgur.com/pbu5sL3.png

another problem with tab 'monitor project' - if i'm in it, i can't click to right-top drop-list Project List and Account, menu just doesn't open
https://i.imgur.com/nK5nkTF.png

it happens even for administrator of mantisbt

**Comment by ghost** [comment]
Theree is a new version, 1.12, which hopefully addresses your issues. Be aware that there is also the Mantis monitor_bug_thershold which can have an impact.. Till now, I have not discovered why you cannot click on Account or Select projects. That is still under investigation

**Comment by pikachurus** [comment]
> Till now, I have not discovered why you cannot click on Account or Select projects. That is still under investigation

 i can click to Account or Select Project from any tab, except 'Monitor Project'

**Comment by pikachurus** [comment]
> Theree is a new version, 1.12, which hopefully addresses your issues. 

now i see 'access denied'  warning instead blank screen with current setting (user with 'developer' role in project, but global role 'reporter', and plugin configuration access set to 'developer') 

but when i change user global role to 'developer' - setting screen available.

**Comment by ghost** [comment]
Ok, look @ version 1.13. Please check the readme section on updating to 1.13 before uploading.
It now is only available in the account menu, no longer in the user maintenance section 9wheer it should not have been in the first place). The authorization level for changing has been removed, it will simply obey to Mantis standard ($g_monitor_bug_threshold).
Think I covered all your issues now:)

**Comment by pikachurus** [comment]
>  it will simply obey to Mantis standard ($g_monitor_bug_threshold).

now it works perfect

> i can click to Account or Select Project from any tab, except 'Monitor Project'

that one fixed too :)

thank you!
